# Generated by Django 4.2.8 on 2024-01-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsentencepair',
            name='sentence_pairs',
            field=models.TextField(),
        ),
    ]
