# Generated by Django 4.2.8 on 2024-01-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_wordsentencepair_sentence_pairs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordsentencepair',
            name='sentence_pairs',
        ),
        migrations.AddField(
            model_name='wordsentencepair',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
