# Generated by Django 4.2.8 on 2024-01-03 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_remove_wordsentencepair_sentence_pairs_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordSentencePair',
        ),
    ]
